### ISSUE TITLE
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"header not found"}}}' 

### ISSUE THREAD

**Issue by minho-comcom-ai** [dorahacksglobal/qf-maci#1]
I tried to vote, but MetaMask show this error:
```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"header not found"}}}' 
```

**Comment by tari404** [comment]
This does not seem to be the problem of the contract, but the problem of the current RPC node of the MATIC network. You can try to refresh the page and try to vote again, and see if you can see your transactions on [polygonscan](https://polygonscan.com/).

reference: https://github.com/MetaMask/metamask-extension/issues/7234
